# SPDX-FileCopyrightText: 2025 Chen Linxuan <me@black-desk.cn>
#
# SPDX-License-Identifier: MIT

name: Continuous integration for master

on:
  push:
    branches:
      - master

jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: black-desk/workflows/generic@master
  autotools:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'head'
      - run: |
          gem install bashcov simplecov-cobertura
      - uses: black-desk/workflows/autotools@master
